# Generated by Django 4.2.3 on 2023-08-18 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studregistration', '0002_studreg_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='studreg',
            name='uname',
            field=models.CharField(default='addNew', max_length=20),
        ),
    ]
